import {
  ArrowLeftRight,
  CopyPlus,
  Dices,
  DoorOpen,
  FastForward,
  Flag,
  Hourglass,
  Locate,
  Maximize,
  MessageSquare,
  Move,
  Plus,
  Pencil,
  Image,
  Send,
  Timer,
  Trash2,
  Eraser,
  RotateCcw,
  Trash,
  Trophy,
  Variable,
  X,
  type LucideIcon
} from "lucide-react"
import type { ActionType } from "@creadordejocs/project-format"

export const ACTION_ICON_MAP: Record<ActionType, LucideIcon> = {
  move: Move,
  setVelocity: FastForward,
  rotate: RotateCcw,
  moveToward: Move,
  clampToRoom: Maximize,
  teleport: Locate,
  destroySelf: Trash,
  destroyOther: X,
  spawnObject: CopyPlus,
  changeSprite: Image,
  setSpriteSpeed: Timer,
  changeScore: Trophy,
  endGame: Flag,
  message: MessageSquare,
  playSound: MessageSquare,
  changeVariable: Variable,
  randomizeVariable: Dices,
  copyVariable: ArrowLeftRight,
  listPush: Plus,
  listSetAt: Pencil,
  listRemoveAt: Trash2,
  listClear: Eraser,
  mapSet: Pencil,
  mapDelete: Trash2,
  mapClear: Eraser,
  goToRoom: DoorOpen,
  restartRoom: RotateCcw,
  wait: Hourglass,
  repeat: RotateCcw,
  forEachList: ArrowLeftRight,
  forEachMap: ArrowLeftRight,
  emitCustomEvent: Send
}

