export const ACTION_LABELS = {
  categories: {
    movement:  "Movement",
    objects:   "Objects",
    game:      "Game",
    variables: "Variables",
    rooms:     "Rooms",
    flow:      "Flow"
  },
  actions: {
    move:              { label: "Move",           shortLabel: "Move" },
    setVelocity:       { label: "Velocity",       shortLabel: "Velocity" },
    rotate:            { label: "Rotate",         shortLabel: "Rotate" },
    moveToward:        { label: "Move Toward",    shortLabel: "Move Toward" },
    clampToRoom:       { label: "Clamp to Room",  shortLabel: "Clamp" },
    teleport:          { label: "Teleport",       shortLabel: "Teleport" },
    destroySelf:       { label: "Destroy Self",   shortLabel: "Destroy Self" },
    destroyOther:      { label: "Destroy Other",  shortLabel: "Destroy Other" },
    spawnObject:       { label: "Spawn Object",   shortLabel: "Spawn Obj." },
    changeSprite:      { label: "Change Sprite",  shortLabel: "Sprite" },
    setSpriteSpeed:    { label: "Sprite Speed",   shortLabel: "Spr. Speed" },
    setObjectText:     { label: "Object Text",    shortLabel: "Text" },
    changeScore:       { label: "Change Score",   shortLabel: "Score" },
    endGame:           { label: "End Game",       shortLabel: "End Game" },
    message:           { label: "Message",        shortLabel: "Message" },
    playSound:         { label: "Sound",          shortLabel: "Sound" },
    changeVariable:    { label: "Variable",       shortLabel: "Variable" },
    randomizeVariable: { label: "Random",         shortLabel: "Random" },
    copyVariable:      { label: "Copy Variable",  shortLabel: "Copy Var." },
    listPush:          { label: "List Push",      shortLabel: "List Push" },
    listSetAt:         { label: "List Set At",    shortLabel: "List Set At" },
    listRemoveAt:      { label: "List Remove At", shortLabel: "List Remove" },
    listClear:         { label: "List Clear",     shortLabel: "List Clear" },
    mapSet:            { label: "Map Set",        shortLabel: "Map Set" },
    mapDelete:         { label: "Map Delete",     shortLabel: "Map Delete" },
    mapClear:          { label: "Map Clear",      shortLabel: "Map Clear" },
    goToRoom:          { label: "Go To Room",     shortLabel: "Go To Room" },
    teleportWindow:    { label: "Teleport Window",shortLabel: "Teleport Win" },
    moveWindow:        { label: "Move Window",    shortLabel: "Move Win." },
    restartRoom:       { label: "Restart Room",   shortLabel: "Restart" },
    wait:              { label: "Wait",           shortLabel: "Wait" },
    repeat:            { label: "Repeat",         shortLabel: "Repeat" },
    forEachList:       { label: "For Each List",  shortLabel: "Each List" },
    forEachMap:        { label: "For Each Map",   shortLabel: "Each Map" },
    emitCustomEvent:   { label: "Emit Event",     shortLabel: "Emit" }
  }
} as const
